name: Node.js custom build job

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Node.js version'
        required: true
        default: 'v22.9.0'
      latest_version:
        description: 'Latest'
        required: true
        default: 'false'

jobs:
  build-custom:
    runs-on: ubuntu-latest

    steps:
      - uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: false
          swap-storage: false

      - name: Check version
        run: |
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          echo "latest_version=${{ github.event.inputs.latest_version }}" >> $GITHUB_ENV
          echo "Node.js current version: ${version}, latest: ${latest_version}"

      - name: Check release
        run: |
          gh release view ${{ env.version }} -R ${{ github.repository }} | grep node-*.tar.gz >/dev/null 2>&1 || echo "create=1" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        if: env.create == '1'
        with:
          path: main

      - name: Create tag
        if: env.create == '1'
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git tag ${{ env.version }}
          git push origin ${{ env.version }} --force
        working-directory: main

      - uses: actions/checkout@v4
        if: env.create == '1'
        with:
          repository: loong64/unofficial-builds
          path: unofficial-builds

      - uses: docker/setup-buildx-action@v3
        if: env.create == '1'

      - name: Set permissions
        if: env.create == '1'
        run: |
          mkdir -p ${{ github.workspace }}/workdir
          sudo chmod -R 777 ${{ github.workspace }}/workdir
          sudo chown -R 1000:docker ${{ github.workspace }}/workdir

      - name: Build node.js
        if: env.create == '1'
        run: |
          ./bin/local_build.sh -r loong64 -v ${{ env.version }} -w ${{ github.workspace }}/workdir
        working-directory: unofficial-builds

      - name: Create release
        if: env.create == '1'
        run: |
          latestFlag=""
          if [ "${{ env.latest_version }}" != "true" ]; then
            latestFlag="--latest=false"
          fi
          gh release create ${{ env.version }} -R ${{ github.repository }} ${{ github.workspace }}/workdir/staging/release/${{ env.version }}/* ${{ github.workspace }}/workdir/staging/src/${{ env.version }}/* ${latestFlag}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}